[workspace]
resolver = "2"

members = [
    "src/database",
    "src/macros",
    "src/mcore",
    "src/parser",
    "src/view",
    "src/utils",

    "src/bin/cli",
    "src/bin/tgbot",
    "src/bin/migrate_db"
]

[workspace.dependencies]
chrono = "0.4"
log = "0.4"
serde = "1.0"
serde_derive = "1.0"
eyre = "0.6"
trees = "0.4"
smartstring = "1"

