[package]
name = "parser"
version.workspace = true
authors.workspace = true
edition.workspace = true

[lib]
path = "./lib.rs"

[dependencies]
mcore = { path = "../mcore" }
utils = { path = "../utils" }

eyre = { workspace = true }
log = { workspace = true }
trees = { workspace = true }
smartstring = { workspace = true }

peg = "0.8"
