[package]
name = "parser"
version.workspace = true
authors.workspace = true
edition.workspace = true

[lib]
path = "./lib.rs"

[dependencies]
solver = { path = "../solver" }
utils = { path = "../utils" }

eyre = { workspace = true }
log = { workspace = true }
smartstring = { workspace = true }
trees = { workspace = true }
itertools = { workspace = true }
serde = { workspace = true }
serde_json = { version = "1.0" }

peg = "0.8"
pyo3 = { version = "0.28", features = ["auto-initialize"] }
