[package]
name = "parser"
version.workspace = true
authors.workspace = true
edition.workspace = true

[lib]
path = "./lib.rs"

[dependencies]
solver = { path = "../solver" }
utils = { path = "../utils" }

eyre = { workspace = true }
log = { workspace = true }
smartstring = { workspace = true }

trees = "0.4"
peg = "0.8"
