//use std::str::FromStr;
use parser::syntax_tree::Node;

grammar;

pub Statements = Vector<Statement, Semicolon>;

Vector<T, Delim> : Vec<T> = {
    <v:(<T> Delim)*> <e:T?> => match e {
        None => v,
        Some(e) => {
            let mut v = v;
            v.push(e);
            v
        }
    }
}

Statement: Box<Node> = {
    Problem,
    Declare,
    Rule,
    Predicate,
};

Problem: Box<Node> = {
    "problem" "{" <c:Conditions> "}" => Box::new(Node{ label: String::from("Problem"),
                                                       childs: c }),
};

Conditions = Vector<Condition, Semicolon>;

Condition: Box<Node> = {
    Rule,
    Predicate,
    Target,
};

Target: Box<Node> = {
    "target" <c:Str> "(" <p:Predicate> ")" => Box::new(Node{ label: String::from("Target"),
                                                             childs: vec!(Box::new(Node{ label: String::from(c),
                                                                                         childs: vec!()}
                                                                                  ),
                                                                          p
                                                                         ),
                                                            }
                                                      ),
    "target" <c:Str> <s:Str> => Box::new(Node{ label: String::from("Target"),
                                               childs: vec!(Box::new(Node{ label: String::from(c),
                                                                           childs: vec!()}
                                                                    ),
                                                            Box::new(Node{ label: String::from(s),
                                                                           childs: vec!()}
                                                                    ),
                                                           )
                                             }
                                        ),
};

Declare: Box<Node> = {
    "symbol" <s:Str> => Box::new(Node{ label: String::from("Declare"),
                                       childs: vec!(Box::new(Node{ label: String::from(s),
                                                                   childs: vec!()}
                                                            ),
                                                    Box::new(Node{ label: String::from("Symbol"),
                                                                   childs: vec!()}
                                                            ),
                                                   )
                                     }
                                ),
    "symbol" <s:SystemOp> => Box::new(Node{ label: String::from("Declare"),
                                            childs: vec!(Box::new(Node{ label: String::from(s),
                                                                        childs: vec!()}
                                                                 ),
                                                         Box::new(Node{ label: String::from("Symbol"),
                                                                        childs: vec!()}
                                                                 ),
                                                        )
                                          }
                                     ),
    "symbol" <s:PredOp> => Box::new(Node{ label: String::from("Declare"),
                                          childs: vec!(Box::new(Node{ label: String::from(s),
                                                                      childs: vec!()}
                                                               ),
                                                       Box::new(Node{ label: String::from("Symbol"),
                                                                      childs: vec!()}
                                                               ),
                                                      )
                                        }
                                   ),
};

Tier<Op, NextTier>: Box<Node> = {
    <l:Tier<Op, NextTier> > <o:Op> <r:NextTier> => Box::new(Node{ label: String::from(o),
                                                                  childs: vec!(l, r)}
                                                           ),
    NextTier
};

Predicate = Tier<LogicOr, AndPred>;
AndPred = Tier<LogicAnd, ElemPred>;

LogicOr = { "||" };
LogicAnd = { "&&" };

ElemPred: Box<Node> = {
    "(" <p:Predicate> ")" => p,
    <l:Expr> <o:PredOp> <r:Expr> => Box::new(Node{ label: String::from(o),
                                                   childs: vec!(l, r)}
                                            ),
};

PredOp = {
    "is",
    "in",
    "==",
    "!=",
    "<=",
    ">=",
    "<",
    ">",
};

Rule: Box<Node> = {
    <l:Predicate> <o:RuleOp> <r:Predicate> =>  Box::new(Node{ label: String::from(o),
                                                              childs: vec!(l, r)}
                                                       ),
};

RuleOp = {
    "=>",
};

Expr = Tier<SumOp, Factor>;
Factor = Tier<MulOp, Eval>;

SumOp = {
    "+",
    "-",
};

MulOp = {
    "*",
    "/",
};

Eval: Box<Node> = {
    "(" <Expr> ")" => <>,
    Term => Box::new(Node{ label: String::from(<>),
                           childs: vec!()}),
    <t:Term> "(" <a:Args> ")" => Box::new(Node{ label: String::from(t),
                                                childs: a }),
    <o:SumOp> <e:Eval> => Box::new(Node{ label: String::from(o),
                                         childs: vec!(e) }),
};

Args = Vector<Expr, Comma>;

Term : &'input str = {
    <s:Str> => s,
};

SystemOp = { "+", "-", "*", "/", }
Str = { r"[A-Za-z0-9_.]+", };

Semicolon = { ";", };

Comma = { ",", };
