#![allow(clippy::all)]

use trees::{tr, Tree};

grammar;

pub Statements = Vector<Statement, Semicolon>;

Vector<T, Delim> : Vec<T> = {
    <v:(<T> Delim)*> <e:T?> => match e {
        None => v,
        Some(e) => {
            let mut v = v;
            v.push(e);
            v
        }
    }
}

Statement: Tree<String> = {
    Problem,
    Declare,
    RuleExt,
    Predicate,
};

Problem: Tree<String> = {
    "problem" "{" <c:Conditions> "}" => {
        let mut t = tr(String::from("Problem"));
        for i in c.iter().cloned() {
            t.push_back(i);
        }
        t
    },
};

Conditions = Vector<Condition, Semicolon>;

Condition: Tree<String> = {
    Rule,
    Predicate,
    Target,
};

Target: Tree<String> = {
    "target" <c:Str> "(" <p:Predicate> ")" => tr(String::from("Target")) /(tr(String::from(c))/p),
    "target" <c:Str> <s:Str> => tr(String::from("Target")) /(tr(String::from(c))/tr(String::from(s))),
};

Attributes = Vector<Eval, Comma>;

Declare: Tree<String> = {
    "symbol" <s:ExtStr> => tr(String::from("Declare")) /(tr(String::from("Symbol"))/tr(String::from(s))),
    "symbol" <s:ExtStr> "{" "attr" <a:Attributes> "}" => {
        let mut t = tr(String::from("Attrs"));
        for i in a.iter().cloned() {
            t.push_back(i);
        }
        tr(String::from("Declare")) /(tr(String::from("Symbol"))/tr(String::from(s))) /t
    }
};

Tier<Op, NextTier>: Tree<String> = {
    <l:Tier<Op, NextTier> > <o:Op> <r:NextTier> => tr(String::from(o))/l/r,
    NextTier
};

RuleExt: Tree<String> = {
    <o:Rule> => o,
    "rule" "{" <r:Rule> ";" <p:Predicates> "}" => {
        let mut t = tr(String::from("Rule"));
        t.push_back(r);
        let mut pred = tr(String::from("Predicates"));
        for i in p.iter().cloned() {
            pred.push_back(i);
        }
        t.push_back(pred);
        t
    },
    "rule" "{" "attr" <a:Attributes> ";" <r:Rule> ";" <p:Predicates> "}" => {
        let mut t = tr(String::from("Rule"));
        t.push_back(r);
        let mut pred = tr(String::from("Predicates"));
        for i in p.iter().cloned() {
            pred.push_back(i);
        }
        let mut attr = tr(String::from("Attributes"));
        for i in a.iter().cloned() {
            attr.push_back(i);
        }
        t.push_back(pred);
        t.push_back(attr);
        t
    }
}

Rule: Tree<String> = {
    <l:Predicate> <o:RuleOp> <r:Predicate> => tr(String::from(o))/l/r,
};

RuleOp = {
    "=>",
    "<=>",
};

Predicates = Vector<Predicate, Semicolon>;

Predicate = Tier<LogicOr, AndPred>;
AndPred = Tier<LogicAnd, ElemPred>;

LogicOr = { "||" };
LogicAnd = { "&&" };

ElemPred: Tree<String> = {
    "!" "(" <p:Predicate> ")" => tr(String::from("!"))/p,
    "(" <p:Predicate> ")" => p,
    "(" <l:Predicate> ")" <o:PredOp> "(" <r:Predicate> ")" => tr(String::from(o))/l/r,
    "(" <l:Predicate> ")" <o:PredOp> <r:Expr> => tr(String::from(o))/l/r,
    <l:Expr> <o:PredOp> <r:Expr> => tr(String::from(o))/l/r,
    "[" <e:Expr> "]" => e,
};

PredOp = {
    "is",
    "in",
    "==",
    "!=",
    "<=",
    ">=",
    "<",
    ">",
};


Expr = Tier<SumOp, Factor>;
Factor = Tier<MulOp, Power>;
Power = Tier<PowOp, Eval>;

PowOp = {
    "^"
}

SumOp = {
    "+",
    "-",
};

MulOp = {
    "*",
    "/",
};

Eval: Tree<String> = {
    "[" <Predicate> "]" => <>,
    "(" <Expr> ")" => <>,
    Term => tr(String::from(<>)),
    <t:Term> "(" <a:Args> ")" => {
        let mut t = tr(String::from(t));
        for i in a.iter().cloned() {
            t.push_back(i);
        }
        t
    },
    <o:SumOp> <e:Eval> => tr(String::from(o))/e
    ,
};

Args = Vector<Expr, Comma>;

Term : &'input str = {
    <s:Str> => s,
};

SystemOp = { "+", "-", "*", "/", }
Str = { 
    r"[A-Za-z0-9_.]+",
    <s:r#"".+""#> => &s[1..s.len()-1]
};

ExtStr = { 
    r"[A-Za-z0-9_.]+",
    "is", "in",
    "==", "!=", "^",
    "<=", ">=", "<", ">",
    "+", "-", "*", "/",
    "&&", "||", "!"
};

Semicolon = { ";", };

Comma = { ",", };
