[package]
name = "view"
version.workspace = true
authors.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
path = "./lib.rs"

[features]
default = ["console"]
console = ["dep:colored"]

[dependencies]
solver = { path = "../solver" }

eyre = { workspace = true }
itertools = { workspace = true }

colored = { version = "3", optional = true }
