[package]
name = "mcore"
version.workspace = true
authors.workspace = true
edition.workspace = true

[lib]
path = "./lib.rs"

[dependencies]
utils = { path = "../utils" }

eyre = { workspace = true }
log = { workspace = true }
serde = { workspace = true }
serde_derive = { workspace = true }
smartstring = { workspace = true }
trees = { workspace = true }

ego-tree = "0.10"

bigdecimal = "0.4"
bincode = "2.0.0-rc.3"
derive_more = { version = "1.0", features = ["full"] }
indexmap = "2.0"
itertools = "0.14"
multimap = { git = "https://github.com/Quotique/multimap.git" }
num = "0.4"
num-bigint = "0.4"
parking_lot = "0.12"

[dev-dependencies]
parser = { path = "../parser" }

insta = "1.42"
