[package]
name = "database"
version.workspace = true
authors.workspace = true
edition.workspace = true

[lib]
path = "./lib.rs"

[dependencies]
solver = { path = "../solver" }

chrono = { workspace = true }
eyre = { workspace = true }
serde = { workspace = true }
serde_derive = { workspace = true }
serde_json = { workspace = true }

blake3 = "1"
redb = "2"
zstd = "0.13"

[dev-dependencies]
tempfile = "3"
