logger:
  filename: "logs/cli.log"
  level: "Trace"
  num_files: 3
  file_rotate_bytes: 100000000
  target_levels:
    mcore: "Info"
    mcore::problem: "Trace"
    mcore::rule: "Trace"
    sled: "Warn"

symbols_dir: "symbols"
problems_dir: "problems"

