logger:
  filename: "logs/cli.log"
  level: "Info"
  num_files: 3
  file_rotate_bytes: 1000000000
  target_levels:
    solver: "Info"
    solver::task: "Trace"
    solver::rule: "Trace"
    redb: "Warn"

symbols_dir: "symbols"
tasks_dir: "tasks/test"

