[package]
name = "utils"
version = "0.4.2"
edition = "2021"

[lib]
path = "./lib.rs"

[dependencies]
chrono = { workspace = true }
log = { workspace = true }
serde = { workspace = true }
serde_derive = { workspace = true }

file-rotate = "0.7.5"
patricia_tree = { version = "0.8" }
slog-async = { version = "2.7" }
slog-scope = { version = "4.4" }
slog-stdlog = { version = "4.1" }
slog-term = { version = "2.9" }
slog = { version = "2.7", features = ["max_level_trace", "release_max_level_trace"] }

[dev-dependencies]
insta = "1.7"
